<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'Blocks of type :title' => 'Các khối thuộc kiểu :title',
  'Blocktype' => 'Kiểu khối',
  'Blocktypes' => 'Các kiểu khối',
  'Blocktypes  :name' => 'Kiểu khối :name',
  'Blocktypes :name' => 'Kiểu khối :name',
  'Component :comp does not valid.' => 'Lớp thành phần :comp không hợp lệ.',
  'Finds a view file based on its name. The view name can be in one of the following formats:<br>
	<ul>
		<li><strong>absolute view within a module:</strong> the view name starts with a single slash <kbd>\'/\'</kbd>. In this case, the view will be searched for under the currently active module\'s view path. If there is no active module, the view will be searched for under the application\'s view path.</li>
		<li><strong>absolute view within the application:</strong> the view name starts with double slashes <kbd>\'//\'</kbd>. In this case, the view will be searched for under the application\'s view path.</li>
		<li><strong>aliased view:</strong> the view name contains dots and refers to a path alias. The view file is determined by calling <code>YiiBase::getPathOfAlias()</code>. Note that aliased views cannot be themed because they can refer to a view file located at arbitrary places.</li>
		<li><strong>relative view:</strong> otherwise. Relative views will be searched for under the currently active controller\'s view path.</li>
	</ul>
	For absolute view and relative view, the corresponding view file is a PHP file whose name is the same as the view name. The file is located under a specified directory. This method will call CApplication::findLocalizedFile to search for a localized file, if any.' => 
	'Tìm một tệp View theo tên được chỉ định. Tên của view có thể có 1 trong các dạng sau:<br>
	<ul>
		<li><strong>Các view file nằm trong một module:</strong> Tên của view bắt đầu bằng một dấu xuộc đơn <kbd>\'/\'</kbd>. Hệ thống sẽ tìm tệp view trong thư mục <kbd>views</kbd> của module hiện thời. Nếu controller hiện tại không thuộc 1 module nào, hệ thống sẽ tìm tiếp trong thư mục <kbd>views</kbd> chung cho ứng dụng..</li>
		<li><strong>Các view file chung cho toàn ứng dụng:</strong> Tên của view bắt đầu bằng 2 dấu xuộc <kbd>\'//\'</kbd>. Hệ thống chỉ quét thư mục <kbd>views</kbd> chung cho toàn ứng dụng.</li>
		<li><strong>Các view file dạng <code>alias</code>:</strong> Tên của view có chứa dấu chấm <kbd>.</kbd>. Hệ thống sẽ dùng hàm <code>YiiBase::getPathOfAlias()</code> để tìm tệp view này. Lưu ý rằng các views dạng này không hỗ trợ chức năng theming, vì nó trỏ tới 1 tệp view cố định.</li>
		<li><strong>Các view tương đối:</strong> Các tên view không thuộc các dạng trên. Các view tương đối sẽ được tìm kiếm trong thư mục views của controller hiện tại.</li>
	</ul>
	Đối với các view tuyệt đối và tương đối, tệp View là một tệp PHP với tên giống với tên view. Tệp này sẽ được đặt trong 1 thư mục được chỉ định. Phương pháp này sẽ gọi <code>CApplication::findLocalizedFile</code> để tìm một tệp đã được ngôn ngữ hóa, nếu có.',
  'Name of this block type. Used in administration interfaces' => 'Tên cho kiểu khối này. Được dùng trong giao diện quản lý của hệ thống.',
  'Prefix for the callback functions.<br> This block configuration will be provided by function <code><em>callback</em>Config</code> while data will be provided by <code><em>callback</em>Data</code> in the component above.' => 'Tiền tố được dùng để chỉ định hàm gọi lại.<br> Form cấu hình cho khối thuộc kiểu này do hàm <code><em>callback</em>Config</code>, còn dữ liệu cung cấp cho view sẽ được cung cấp bởi hàm <code><em>callback</em>Data</code> trong lớp thành phần được chỉ định.',
  'The view file this block type will use. Provided as Yii path alias format.' => 'Tên tệp view mà các khối loại này sẽ dùng.',
  'Viewfile :view does not valid.' => 'Tệp view :view không tồn tại.',
  'Yii Component that provide Callback Data and Config functions, written in Yii path alias.' => 'Lớp thành phần Yii cung cấp các hàm callback để cung cấp dữ liệu và cấu hình cho khối. Nhập dưới dạng đường dẫn ảo của Yii.',
  'Btid' => 'Mã',
  'Callback' => 'Hàm gọi lại',
  'Component' => 'Lớp thành phần',
  'Description' => 'Mô tả',
  'Title' => 'Tiêu đề',
  'Viewfile' => 'Tệp View',
);
