<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'Contact Us'	=>	'Liên hệ với chúng tôi',
  'If you have business inquiries or other questions, please fill out the following form to contact us. Thank you.' =>
  'Nếu bạn có thắc mắc hay góp ý gì với chúng tôi, xin hãy điền và gửi mẫu dưới đây tới cho chúng tôi. Cám ơn bạn đã ghé thăm website.',
  'Body' => 'Nội dung',
  'Email' => 'Địa chỉ Email',
  'Name' => 'Họ tên',
  'Subject' => 'Tiêu đề',
  'Verification Code' => 'Mã kiểm tra',
);
