<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'Createtime' => 'Ngày tạo',
  'Description' => 'Thông tin mô tả',
  'Entity' => 'Lớp gắn kết',
  'Ext' => 'Phần mở rộng',
  'File' => 'Tệp tin',
  'Files' => 'Các tệp tin',
  'ID' => 'ID',
  'Missing audio file: %file' => 'Tệp âm thanh <em>%file</em> không tồn tại.',
  'Missing image file: %file' => 'Tệp ảnh <em>%file</em> không tồn tại.',
  'Name' => 'Tên',
  'Path' => 'Đường dẫn',
  'Pkey' => 'Khóa liên kết',
  'Size' => 'Kích thước',
  'The file :file is removed.' => 'Tệp :file đã bị xóa khỏi hệ thống',
  'Title' => 'Tiêu đề',
  'Type' => 'Kiểu tệp tin',
  'Updatetime' => 'Ngày sửa đổi',
  '_HINT_File.description' => 'Nhập các nội dung mô tả liên quan đến tệp tin được tải lên.',
  '_HINT_File.entity' => 'Lớp PHP được cấp quyền sở hữu tệp tin này.',
  '_HINT_File.name' => 'Tên tệp, không bao gồm phần mở rộng',
  '_HINT_File.path' => 'Đường dẫn tương đối của tệp trên server',
  '_HINT_File.pkey' => 'Khóa liên kết tới 1 đối tượng trên lớp gắn kết',
  '_HINT_File.title' => 'Tên dễ nhớ của tệp tin, giúp quản lý dễ dàng hơn.',
);
