<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Hello, ' => 'Xin chào,',
  'Logout' => 'Đăng xuất',
  'Clear Filters' => 'Bỏ lọc',
  'Create' => 'Tạo',
  'Data deleted!' => 'Đã xóa dữ liệu!',
  'Data saved!' => 'Đã lưu dữ liệu!',
  'Delete' => 'Xóa',
  'Manage' => 'Quản lý',
  'The requested page does not exist.' => 'Không tìm thấy trang',
  'Update' => 'Cập nhật',
  'You may optionally enter a comparison operator (<b>&lt;</b>, <b>&lt;=</b>, <b>&gt;</b>, <b>&gt;=</b>, <b>&lt;&gt;</b> or <b>=</b>) at the beginning of each of your search values to specify how the comparison should be done.' => '',
  'Attached' => 'Gắn',
  'Name' => 'Tên',
  'Rules' => 'Luật',
  'Type' => 'Kiểu',
  'Viewfile' => 'Tệp view',
  'Widget' => 'Widget',
  'Admin' => 'Quản lý',
  'Advanced Search' => 'Tìm kiếm nâng cao',
  'Cancel' => 'Hủy bỏ',
  'Clear Filters' => 'Bỏ lọc',
  'Configure' => 'Cấu hình',
  'Continue Delete' => 'Tiếp tục xóa',
  'Create' => 'Tạo',
  'Createtime' => 'Thời gian tạo',
  'Data saved!' => 'Đã lưu dữ liệu!',
  'Delete' => 'Xóa',
  'Delete Confirmation' => 'Xác nhận việc xóa',
  'Description' => 'Mô tả',
  'Duplicate' => 'Sao chép',
  'Export :type' => 'Xuất :type',
  'Fields with <span class="required">*</span> are required.' => 'Các trường với dấu <span class="required">*</span> không được phép rỗng.',
  'Hello, ' => 'Xin chào, ',
  'Home' => 'Trang chủ',
  'Index' => 'Danh mục',
  'List' => 'Danh sách',
  'Logout' => 'Đăng xuất',
  'Manage' => 'Quản lý',
  'No' => 'Không',
  'Preview' => 'Xem thử',
  'Save' => 'Lưu',
  'Save Settings' => 'Lưu thiết lập',
  'Search' => 'Tìm kiếm',
  'Settings' => 'Thiết lập',
  'Sort' => 'Sắp xếp',
  'The page you requested was not found.' => 'Không tìm thấy trang được yêu cầu.',
  'The requested page does not exist.' => 'Địa chỉ web không tồn tại.',
  'Theme' => 'Giao diện',
  'Title' => 'Tiêu đề',
  'Update' => 'Cập nhật',
  'View' => 'Xem',
  'Yes' => 'Có',
  'You may use <a target="_blank" href="http://daringfireball.net/projects/markdown/syntax">Markdown syntax</a>.' => 'Bạn có thể sử dụng <a target="_blank" href="http://daringfireball.net/projects/markdown/syntax">cú pháp Markdown</a> trong ô này.',
  'index' => '',
);
