<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  '-- Select region --' => '-- Chọn vùng trình bày --',
  'Advanced Search' => 'Tìm kiếm nâng cao',
  'Are you sure you want to delete this Block :name?' => 'Bạn có chắc là muốn xóa khối ":name" này chứ?',
  'Bid' => 'Mã',
  'Block types provide various features to the CMS. Each block type will have its own behaviors.' => 'Mỗi loại khối lại cung cấp các tính năng mở rộng cho CMS.',
  'Blocks' => 'Khối',
  'Blocks :name' => 'Khối :name',
  'Cancel' => 'Thôi',
  'Duplicate' => 'Sao chép',
  'Configuration for block :block' => 'Cấu hình khối :block',
  'Continue Delete' => 'Tiếp tục xóa',
  'Continue Delete ' => 'Tiếp tục xóa',
  'Create' => 'Tạo',
  'Delete Confirmation' => 'Xác nhận thao tác xóa',
  'Description' => 'Mô tả',
  'Display' => 'Hiển thị',
  'Fields with' => 'Các trường',
  'If specified, the block will be render to the end users with this label.' => 'Khi trình bày, khối này sẽ kèm theo tiêu đề được nhập',
  'Index' => 'Danh sách',
  'Label' => 'Nhãn',
  'List' => 'Liệt kê',
  'Manage' => 'Quản lý',
  'No' => 'Không',
  'Option' => 'Cấu hình',
  'Position of the Portlet displayed in theme :theme' => 'Vị trí của khối khi trình bày trên giao diện :theme',
  'Preview' => 'Xem thử',
  'Region in :theme' => 'Vùng hiển thị trong :theme',
  'Save' => 'Lưu',
  'Search' => 'Tìm kiếm',
  'Settings' => 'Thiết lập',
  'Status' => 'Trạng thái',
  'Temporary disable this block.' => 'Tạm thời không hiển thị khối này.',
  'The region in theme :theme' => 'Vùng hiển thị trên giao diện :theme',
  'Theme Configure for Block :block' => 'Cấu hình cho khối :block trên các giao diện',
  'Title' => 'Tên khối',
  'Title of this block, to be displayed on Administration page.' => 'Tên hiển thị trên các giao diện quản lý của hệ thống',
  'Type' => 'Kiểu khối',
  'Update' => 'Cập nhật',
  'Url' => 'Địa chỉ URL',
  'View' => 'Chi tiết',
  'Weight in :theme' => 'Sắp xếp trên giao diện :theme',
  'Yes' => 'Có',
  'You may use <a target="_blank" href="http://daringfireball.net/projects/markdown/syntax">Markdown syntax</a>.' =>
  'Nội dung hỗ trợ <a target="_blank" href="http://daringfireball.net/projects/markdown/syntax">cú pháp Markdown</a>.',
  '_HINT_Block.description' => 'Thông tin mô tả cho khối',
  '_HINT_Block.display' => 'Cách trình bày khối',
  '_HINT_Block.label' => 'Tiêu đề sẽ hiển thị kèm theo khi trình bày khối',
  '_HINT_Block.option' => 'Các thiết lập cho khối',
  '_HINT_Block.status' => 'Bỏ dấu hộp kiểm để tạm thời bỏ qua, không hiển thị khối trên hệ thống.',
  '_HINT_Block.title' => '',
  '_HINT_Block.type' => 'Kiểu khối quyết định cách cấu hình và nội dung cung cấp cho khối.',
  '_HINT_Block.url' => 'Địa chỉ URL để lọc dữ liệu',
  'are required' => 'là cần thiết',
  'index' => 'Chỉ mục',
  '{relation}' => '{relation}',
  'Block' => 'Khối',
  'Block Preview' => 'Xem thử khối',
  'Block Themes' => 'Giao diện - khối',
  'Create Block' => 'Tạo khối mới',
  'Invalid request. Please do not repeat this request again.' => 'Yêu cầu không hợp lệ. Xin vui lòng không thử lại.',
  'List Block' => 'Danh sách khối',
  'Manage Blocks' => 'Quản lý khối',
  'Information'		=>	'Thông tin về khối',
  'Display Settings'	=>	'Thiết lập hiển thị',
  'Usage'	=>	'Được sử dụng',
  'Configure' => 'Thiết lập',
  'Theme'	=>	'Sử dụng',
  'Delete'	=>	'Xóa',
  'All pages except those listed' => 'Tất cả các trang, trừ các trang dưới đây',
  'Only the listed pages' => 'Chỉ các trang dưới đây',
);
