<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Category' => '',
  'Comments' => '',
  'Contents' => '',
  'Files' => '',
  'Menu' => '',
  'Tags' => '',
  '' => '',
  '--- Select Parent Category ---' => '',
  'Admin' => '',
  'Advanced Search' => '',
  'Alias' => '',
  'Archived' => '',
  'Bizrule' => '',
  'Body' => '',
  'Cancel' => '',
  'Categories' => '',
  'Cid' => '',
  'Create' => '',
  'Createtime' => '',
  'Data' => '',
  'Description' => '',
  'Draft' => '',
  'Duplicate' => '',
  'Fields with <span class="required">*</span> are required.' => '',
  'File' => '',
  'Icon' => '',
  'Id' => '',
  'Index' => '',
  'Label' => '',
  'Level' => '',
  'Lft' => '',
  'List' => '',
  'Manage' => '',
  'Name' => '',
  'Nodes' => '',
  'Published' => '',
  'Rgt' => '',
  'Root' => '',
  'Save' => '',
  'Search' => '',
  'Settings' => '',
  'Sort' => '',
  'Status' => '',
  'Task' => '',
  'Template' => '',
  'Title' => '',
  'Type' => '',
  'Uid' => '',
  'Updatetime' => '',
  'Url' => '',
  'User' => '',
  'Visible' => '',
  '_HINT_Node.body' => '',
  '_HINT_Node.category' => '',
  '_HINT_Node.tags' => '',
  '_HINT_Node.title' => '',
);
