<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Last updated on %update' => '',
  'Posted by <strong>%user</strong> on <time>%pubdate</time>' => '',
  'Tags: %tags' => '',
  '--- Select Parent Category ---' => '--- Chọn cấp trên ---',
  'Admin' => 'Quản lý',
  'Advanced Search' => 'Tìm kiếm nâng cao',
  'Alias' => 'Bí danh',
  'Archived' => 'Lưu trữ',
  'Body' => 'Thân bài',
  'Cancel' => 'Thôi',
  'Categories' => 'Các chuyên mục',
  'Category' => 'Chuyên mục',
  'Category :name' => 'Chuyên mục :name',
  'Children category of :category' => 'Chuyên mục cấp dưới của :category',
  'Cid' => '',
  'Comments' => 'Bình luận',
  'Content' => 'Nội dung',
  'Contents' => 'Các nội dung',
  'Create' => 'Tạo',
  'Createtime' => 'Thời gian tạo',
  'Delete' => 'Xóa',
  'Description' => 'Mô tả',
  'Draft' => 'Nháp',
  'Duplicate' => 'Sao chép',
  'Fields with <span class="required">*</span> are required.' => 'Các trường <span class="required">có dấu sao *</span> không được để trống.',
  'Files' => 'Tệp tin',
  'Id' => 'Mã',
  'Index' => 'Danh sách',
  'Level' => 'Cấp',
  'Lft' => 'Trái',
  'Manage' => 'Quản lý',
  'Node' => 'Mục nội dung',
  'Nodes' => 'Các nội dung',
  'Published' => 'Đã xuất bản',
  'Rgt' => 'Phải',
  'Root' => 'Gốc',
  'Save' => 'Lưu',
  'Search' => 'Tìm kiếm',
  'Sort' => 'Sắp xếp',
  'Status' => 'Trạng thái',
  'Tags' => 'Thẻ',
  'Title' => 'Tiêu đề',
  'Uid' => 'Mã người dùng',
  'Update' => 'Cập nhật',
  'Updatetime' => 'Thời gian cập nhật',
  'User' => 'Người dùng',
  'View' => 'Xem',
  'You may use <a target="_blank" href="http://daringfireball.net/projects/markdown/syntax">Markdown syntax</a>.' => '',
  '_HINT_Category.root' => '',
  '_HINT_Category.title' => '',
  '_HINT_Node.body' => '',
  '_HINT_Node.category' => '',
  '_HINT_Node.tags' => '',
  '_HINT_Node.title' => '',
);
