<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'Node' => 'Bài viết',
  '-- Select Category for Node --' => '-- Chọn chuyên mục cho bài viết --',
  '--- Select Parent Category ---' => '-- Chọn chuyên mục cho bài viết --',
  'Are you sure you want to delete this Node :name?' => 'Bạn có tiếp tục xóa bài viết :name này không?',
  'Body' => 'Nội dung',
  'Category' => 'Chuyên mục',
  'Category: %category' => 'Chuyên mục: %category',
  'Createtime' => 'Ngày đăng',
  'Last updated on %update' => 'Cập nhật lần cuối: %update',
  'Node Settings' => 'Thiết lập bài viết',
  'Nodes' => 'Các bài viết',
  'Posted by <strong>%user</strong> on <time>%pubdate</time>' => 'Đăng bởi <strong>%user</strong>, <time>%pubdate</time>',
  'Select the parent Category for type Node' => 'Chọn cây Chuyên mục cho kiểu Bài viết',
  'Tags' => 'Thẻ phân loại',
  'Tags for Node' => 'Các thẻ phân loại cho bài viết',
  'Tags: %tags' => 'Thẻ phân loại: %tags',
  'Title' => 'Tiêu đề',
  'Updatetime' => 'Ngày cập nhật',
  '_HINT_Node.body' => 'Nhập nội dung bài viết. Bạn có thể chèn thêm ảnh, liên kết, hoặc sao chép từ Word thông qua các công cụ trên thanh Toolbar.',
  '_HINT_Node.category' => 'Chọn chuyên mục sẽ đăng bài viết này.',
  '_HINT_Node.cid' => 'Chọn chuyên mục sẽ đăng bài viết này.',
  '_HINT_Node.status' => '',
  '_HINT_Node.tags' => 'Nhập các thẻ (từ khóa) liên quan đến bài viết, phân tách bằng dấu phẩy <kbd>,</kbd>',
  '_HINT_Node.title' => 'Tiêu đề của bài viết',
  'body' => 'nội dung',
  'cid' => 'chuyên mục',
  'status' => 'trạng thái',
  'tags' => 'thẻ phân loại',
  'title' => 'tiêu đề',
);
