<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Business rule' => '',
  'A role is group of permissions to perform a variety of tasks and operations, for example the authenticated user.' => 'Mỗi vai trò được phép thực hiện nhiều hành động.',
  'A task is a permission to perform multiple operations, for example accessing a group of controller action.' => 'Một tác vụ bao gồm nhiều hành động.',
  'An operation is a permission to perform a single operation, for example accessing a certain controller action.' => 'Mỗi hành động cho phép thực hiện 1 thao tác',
  'Application' => '',
  'Assign item' => 'Gán một mục',
  'Assignment' => 'Gán quyền',
  'Assignments' => 'Gán quyền',
  'Assignments for :username' => 'Gán quyền cho :username',
  'AuthItem' => 'Quyền',
  'Authorization items can be managed under {roleLink}, {taskLink} and {operationLink}.' => '',
  'Cancel' => 'Thôi',
  'Code that will be executed when performing access checking.' => '',
  'Create :type' => 'Tạo :type',
  'Create Role' => '',
  'Create a new operation' => 'Tạo thao tác',
  'Create a new role' => 'Tạo vai trò mới',
  'Create a new task' => 'Tạo Tác vụ',
  'Data' => 'Dữ liệu',
  'Description' => 'Mô tả',
  'Do not change the name unless you know what you are doing.' => 'Không đổi tên trừ phi biết rõ về hoạt động của module',
  'Generate' => '',
  'Generate items' => '',
  'Generate items for controller actions' => '',
  'Here you can view and manage the permissions assigned to each role.' => '',
  'Here you can view which permissions has been assigned to each user.' => 'Danh sách các quyền được gán cho mỗi người dùng',
  'Hover to see from where the permission is inherited.' => '',
  'Install' => 'Cài đặt',
  'Item' => '',
  'Modules' => '',
  'Name' => 'Tên',
  'No assignments available to be assigned to this user.' => 'Không có mục nào có thể gán được cho người dùng này',
  'No authorization items found.' => '',
  'No operations found.' => 'Không có thao tác',
  'No roles found.' => 'Không có vai trò',
  'No tasks found.' => 'Không thấy tác vụ nào',
  'No users found.' => 'Không có người dùng nào',
  'Operation' => 'Hành động',
  'Operations' => 'Hành động',
  'Operations exist below tasks in the authorization hierarchy and can therefore only inherit from other operations.' => '',
  'Permissions' => 'Quyền',
  'Please select which items you wish to generate.' => '',
  'Revoke' => 'Bỏ cấp quyền',
  'Rights' => 'Phân quyền',
  'Role' => 'Vai trò',
  'Roles' => 'Vai trò',
  'Roles exist at the top of the authorization hierarchy and can therefore inherit from other roles, tasks and/or operations.' => 'Vai trò là cấp cao nhất trên cây phân quyền. Nó có thể kế thừa các Tác Vụ và Vai trò khác.',
  'Save' => 'Lưu',
  'Select all' => '',
  'Select none' => '',
  'Source' => '',
  'Task' => 'Thao tác',
  'Tasks' => 'Các thao tác',
  'Tasks exist below roles in the authorization hierarchy and can therefore only inherit from other tasks and/or operations.' => 'Tác vụ nằm thấp hơn so với Vai trò trong cây phân quyền. Nó kế thừa được các tác vụ hoặc hành động khác.',
  'This user has not been assigned any items.' => 'Chưa có quyền nào được cấp cho người này',
  'Type' => 'Loại',
  'Values within square brackets tell how many children each item has.' => 'Số quyền cấp dưới được ghi trong ngoặc vuông',
  'You are not authorized to perform this action.' => 'Bạn không được cấp quyền truy cập vào trang này.',
);
