<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'Ancestors of Webmenu :item' => 'Các menu cấp trên của :item',
  'Webmenu' => 'Trình đơn',
  'Web Menus' => 'Trình đơn',
  'Configuration for Menu Portlet.' => 'Thiết lập cho Portlet Menu',
  'Decendances of Webmenu :item' => 'Các menu cấp dưới của :item',
  'View Webmenu :item' => 'Xem menu :item',
  '-- Select Parent Menu --' => '-- Chọn menu cấp cha --',
  '<strong>%title</strong>: %desc' => '<strong>%title</strong>: %desc',
  'Are you sure you want to delete this Webmenu :name?' => 'Xin hãy xác nhận thao tác xóa menu :name.',
  'Description' => 'Mô tả',
  'ID' => 'ID',
  'Label' => 'Nhãn',
  'Level' => 'Cấp bậc',
  'Lft' => 'Nhánh trái',
  'Menu Portlet Configuration' => 'Cấu hình menu Portlet',
  'Rgt' => 'Nhánh phải',
  'Root' => 'Cấp cha',
  'Sort' => 'Sắp xếp',
  'Sort Web Menu :title' => 'Sắp xếp menu :title',
  'Template' => 'Mẫu menu',
  'Url' => 'Địa chỉ URL',
  'Visible' => 'Hiển thị',
  'Web Menu' => 'Menu',
  '_HINT_Webmenu.description' => 'Thông tin mô tả ngắn gọn cho một mục menu. Sẽ được hiển thị dưới dạng tooltip khi người dùng di chuột vào menu.',
  '_HINT_Webmenu.icon' => 'Biểu tượng sẽ được đặt bên cạnh phần văn bản của menu',
  '_HINT_Webmenu.label' => 'Văn bản hiển thị trên mục menu này.',
  '_HINT_Webmenu.root' => 'Menu cấp trên',
  '_HINT_Webmenu.task' => 'Phân quyền mà menu này được gán',
  '_HINT_Webmenu.template' => 'Mẫu trình bày menu',
  '_HINT_Webmenu.url' => 'Địa chỉ URL của menu',
  '_HINT_Webmenu.visible' => 'Hiển thị menu này hay tạm ẩn nó đi?',
  'description' => 'Thông tin mô tả',
  'icon' => 'Biểu tượng',
  'label' => 'Nhãn',
  'root' => 'Cấp cha',
  'template' => 'Mẫu hiển thị',
  'url' => 'Địa chỉ URL',
  'visible' => 'Hiển thị',
);
