<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'Webtheme' => 'Giao diện',
  'Available Webtheme' => 'Các giao diện',
  'Available Region'	=>	'Các vùng được hỗ trợ',
  'Configuration for Custom Content.' => 'Cấu hình cho nội dung tự soạn',
  'Configure Theme Settings' => 'Cấu hình các thiết lập giao diện',
  'Configure Webtheme' => 'Cấu hình giao diện',
  'Contact Email' => 'Email liên hệ',
  'Content' => 'Nội dung',
  'Dummy portlet on region :region' => 'Portlet mẫu cho vùng :region',
  'No description available' => 'Không có thông tin mô tả',
  'Records per Page' => 'Số bản ghi trên mỗi trang',
  'Server Email' => 'Email của Server',
  'Site Name' => 'Tên website',
  'Site Logo' => 'Logo cho website',
  'Site Slogan' => 'Slogan cho website',
  'Website Layout' => 'Layout cho website',
  'Website Theme' => 'Giao diện cho website',
  'You can customize the theming of this region by edit the layout file, and put the variable <code>$:region</code> into the region.' => 'Để tùy biến giao diện cho vùng này, hãy sửa lại tệp layout và đưa thêm vào biến <code>$:region</code> vào trong vùng phù hợp.',
  // Hints
  '_HINT_Webtheme.siteName' => 'Văn bản sẽ được hiển thị trên phần đầu trang và trên tiêu đề của cửa sổ trình duyệt.',
  '_HINT_Webtheme.siteSlogan'	=>	'Văn bản thường được hiển thị bên dưới phần tên trang.',
  '_HINT_Webtheme.siteLogo'		=>	'Phần logo ở bên cạnh tên trang và slogan.',
  '_HINT_Webtheme.theme'	=>	'Giao diện mà website sẽ sử dụng.',
  '_HINT_Webtheme.serverEmail'	=>	'Địa chỉ Email dùng để gửi thư tới các người dùng trên hệ thống',
  '_HINT_Webtheme.contactEmail'	=>	'Địa chỉ Email dùng để chuyển tiếp các thư liên hệ do người tham quan website gửi tới thông qua trang <em>Liên hệ</em>.',
  '_HINT_Webtheme.homeUrl'	=>	'Đường dẫn dùng làm trang chủ.',
  '_HINT_Webtheme.perPage'	=>	'Số bản ghi trên các giao diện liệt kê dưới dạng bảng trong phần quản trị.',
  '_HINT_Webtheme.layout'	=>	'View được dùng làm layout mặc định cho hệ thống.',
  
);
